const TrackingCodes = [
  { code: 'A', desc: 'Arrived' },
  { code: 'A3', desc: 'Shipment returned to shipper' },
  { code: 'A5', desc: 'Unable to locate' },
  { code: 'A7', desc: 'Refused by consignee' },
  { code: 'A9', desc: 'Shipment damaged' },
  { code: 'AA', desc: 'Pickup appointmnet Date/Time' },
  { code: 'AB', desc: 'Delivery appointment Date/Time' },
  { code: 'AD', desc: 'Delivert appointment scheduled' },
  { code: 'AF', desc: 'Completed loading at pickup location' },
  { code: 'AG', desc: 'Estimated delivery' },
  { code: 'AH', desc: 'Attempted delivery' },
  { code: 'AI', desc: 'Shipment has been reconsigned' },
  { code: 'AJ', desc: 'Tendered for delivery' },
  { code: 'AM', desc: 'Loaded on truck' },
  { code: 'AN', desc: 'Diverted to air carrier' },
  { code: 'AP', desc: 'Delivery not completed' },
  { code: 'AR', desc: 'Rail arrival at destination intermodal ramp' },
  { code: 'AV', desc: 'Available for delivery' },
  { code: 'AW', desc: 'Past cut-ff time' },
  { code: 'B', desc: 'Damaged' },
  { code: 'B2', desc: 'Trap for customer' },
  { code: 'B6', desc: 'Estimated to arrive at carrier terminal' },
  { code: 'BA', desc: 'Connecting line or cartage pick-up' },
  { code: 'BC', desc: 'Storage in transit' },
  { code: 'BG', desc: 'Info / General status' },
  { code: 'BH', desc: 'Insufficient time to complete delivery' },
  { code: 'BI', desc: 'Cartage agent' },
  { code: 'BS', desc: 'Refused by customer' },
  { code: 'C1', desc: 'Estimated to depart terminal location' },
  { code: 'CA', desc: 'Shipment cancelled' },
  { code: 'CD', desc: 'Carrier departed delivery location' },
  { code: 'CL', desc: 'Trailer closed out' },
  { code: 'CP', desc: 'Completed loading at pick-up location' },
  { code: 'D1', desc: 'Completed unloading at delivery location' },
  { code: 'E', desc: 'Estimated to arrive (En Route)' },
  { code: 'HB', desc: 'Held - Refused' },
  { code: 'HC', desc: 'Held - Consignee closed' },
  { code: 'HD', desc: 'Held - Refused shipment' },
  { code: 'I1', desc: 'In - Gate' },
  { code: 'J', desc: 'Delivered to connecting line' },
  { code: 'J1', desc: 'Delivered to connecting line' },
  { code: 'K', desc: 'Customs' },
  { code: 'K1', desc: 'Arrived at customs' },
  { code: 'L', desc: 'Loading' },
  { code: 'L1', desc: 'Loading' },
  { code: 'NS', desc: 'Normal status' },
  { code: 'OA', desc: 'Out-Gate' },
  { code: 'OO', desc: 'Paperwork received' },
  { code: 'P', desc: 'Departure from location' },
  { code: 'P1', desc: 'Departed terminal location' },
  { code: 'PR', desc: 'U.S Customs hold at in-bound location' },
  { code: 'R1', desc: 'Received from prior carrier' },
  { code: 'RB', desc: 'Delivery appointment requested' },
  { code: 'RL', desc: 'Rail departure from origin intermodal ramp' },
  { code: 'S1', desc: 'Trailer spotted at consignee' },
  { code: 'SD', desc: 'Shipment delayed' },
  { code: 'T', desc: 'At terminal: Intra-terminal movement' },
  { code: 'TN', desc: 'Trailer reference' },
  { code: 'WE', desc: 'Weather prevented movement' },
  { code: 'X1', desc: 'Arrived at delivery location' },
  { code: 'X2', desc: 'Estimated date and/or time of arrival at consignees location' },
  { code: 'X3', desc: 'Arrived at pick-up location' },
  { code: 'X4', desc: 'Arrived at terminal location' },
  { code: 'X5', desc: 'Arrived at delivery location' },
  { code: 'X6', desc: 'En Route to develivery location' },
  { code: 'X8', desc: 'Arrived at pick-up location loading dock' },
  { code: 'X9', desc: 'Delivery appointment secured on this date and/or time' },
  { code: 'XB', desc: 'Shipment acknowledged' },
  { code: 'Z1', desc: 'Client shipment update' },
  { code: 'Z2', desc: 'Image received' }
]

export const getTrackingCodeDescription = (code: string): string => {
  const trackingCode = TrackingCodes.find( trackingCode => (trackingCode.code === code) )
  if(trackingCode) return trackingCode.desc
  return 'Unknown description'
}